# Generated by Django 4.0.2 on 2022-02-20 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('google', '0002_alter_question_q_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choices',
            old_name='choice',
            new_name='text',
        ),
        migrations.AlterField(
            model_name='question',
            name='q_type',
            field=models.IntegerField(choices=[(3, 'انتخابی'), (1, 'پاراگراف'), (2, 'کوتاه'), (0, 'چندگزینه ای')], default=0, verbose_name='نوع سوال'),
        ),
    ]
