# Generated by Django 4.0.2 on 2022-02-20 15:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('google', '0004_alter_question_q_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='creator',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='سازنده'),
        ),
        migrations.AlterField(
            model_name='question',
            name='q_type',
            field=models.IntegerField(choices=[(0, 'کوتاه'), (2, 'چندگزینه ای'), (1, 'پاراگراف'), (3, 'انتخابی')], default=0, verbose_name='نوع سوال'),
        ),
    ]
