# Generated by Django 4.0.2 on 2022-02-22 08:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('google', '0006_alter_question_q_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='سازنده'),
        ),
        migrations.AlterField(
            model_name='form',
            name='questions',
            field=models.ManyToManyField(related_name='questions', to='google.Question', verbose_name='سوالات'),
        ),
        migrations.AlterField(
            model_name='question',
            name='choices',
            field=models.ManyToManyField(blank=True, related_name='+', to='google.Choices', verbose_name='پاسخ ها'),
        ),
        migrations.AlterField(
            model_name='question',
            name='q_type',
            field=models.IntegerField(choices=[(0, 'کوتاه'), (1, 'پاراگراف'), (2, 'انتخابی'), (3, 'چندگزینه ای')], default=0, verbose_name='نوع سوال'),
        ),
    ]
