# Generated by Django 4.0.2 on 2022-02-22 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('google', '0007_alter_form_creator_alter_form_questions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='choices',
            field=models.ManyToManyField(blank=True, related_name='choices', to='google.Choices', verbose_name='پاسخ ها'),
        ),
        migrations.AlterField(
            model_name='question',
            name='q_type',
            field=models.IntegerField(choices=[(3, 'چندگزینه ای'), (1, 'پاراگراف'), (0, 'کوتاه'), (2, 'انتخابی')], default=0, verbose_name='نوع سوال'),
        ),
    ]
