# Generated by Django 4.0.2 on 2022-02-22 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('google', '0010_rename_choices_choice_alter_question_q_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='questions',
            field=models.ManyToManyField(blank=True, related_name='questions', to='google.Question', verbose_name='سوالات'),
        ),
        migrations.AlterField(
            model_name='question',
            name='choices',
            field=models.ManyToManyField(blank=True, related_name='choices', to='google.Choice', verbose_name='پاسخ ها'),
        ),
        migrations.AlterField(
            model_name='question',
            name='q_type',
            field=models.IntegerField(choices=[(1, 'پاراگراف'), (0, 'کوتاه'), (3, 'چندگزینه ای'), (2, 'انتخابی')], default=0, verbose_name='نوع سوال'),
        ),
    ]
