# Generated by Django 4.0.2 on 2022-02-23 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('google', '0011_alter_form_questions_alter_question_choices_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='q_type',
            field=models.IntegerField(choices=[(0, 'کوتاه'), (1, 'پاراگراف'), (3, 'چندگزینه ای'), (2, 'انتخابی')], default=0, verbose_name='نوع سوال'),
        ),
    ]
