# Generated by Django 4.0.2 on 2022-02-28 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('google', '0012_alter_question_q_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='q_type',
            field=models.IntegerField(choices=[(1, 'پاراگراف'), (2, 'انتخابی'), (3, 'چندگزینه ای'), (0, 'کوتاه')], default=0, verbose_name='نوع سوال'),
        ),
    ]
